In [2]:
import numpy as np
import random

In [ ]:
# Codercise l.1.1 - Normalization of quantum states

ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])


def normalize_state(alpha, beta):
    """Compute a normalized quantum state given arbitrary amplitudes.

    Args:
        alpha (complex): The amplitude associated with the |0> state.
        beta (complex): The amplitude associated with the |1> state.

    Returns:
        np.array[complex]: A vector (numpy array) with 2 elements that represents
        a normalized quantum state.
    """

    state = np.array([alpha, beta])

    norm = np.sqrt(np.abs(alpha)**2 + np.abs(beta)**2)

    norm_state = state / norm

    return norm_state

normalize_state(1/2, 3/2)


array([0.31622777, 0.9486833 ])

In [ ]:
# Codercise l.1.2 - Inner product and orthonormal bases

def inner_product(state_1, state_2):
    """Compute the inner product between two states.

    Args:
        state_1 (np.array[complex]): A normalized quantum state vector
        state_2 (np.array[complex]): A second normalized quantum state vector

    Returns:
        complex: The value of the inner product <state_1 | state_2>.
    """

    inner = state_1.conj().T @ state_2

    return inner


# Test your results with this code
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])

state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 

print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")
print(f"<state_1|state_2> = {inner_product(state_1, state_2)}")


<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1
<state_1|state_2> = (0.565685424949238+0.42426406871192845j)


In [ ]:
# Codercise l.1.3 - Sampling measurements outcome

def measure_state(state, num_meas):
    """Simulate a quantum measurement process.

    Args:
        state (np.array[complex]): A normalized qubit state vector.
        num_meas (int): The number of measurements to take

    Returns:
        np.array[int]: A set of num_meas samples, 0 or 1, chosen according to the probability
        distribution defined by the input state.
    """

    prob_0 = np.abs(state[0]**2)
    prob_1 = np.abs(state[1]**2)

    measurements = np.random.choice([0, 1], p=[prob_0, prob_1], size=num_meas)

    return measurements

measure_state(np.array([0.8, 0.6]), 10)


array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
# Codercise l.1.4 - Applying a quantum operation

U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
U_2 = np.array([[0, 1], [1, 0]])


def apply_u(state):
    """Apply a quantum operation.

    Args:
        state (np.array[complex]): A normalized quantum state vector.

    Returns:
        np.array[complex]: The output state after applying U.
    """

    new_state = np.dot(U, state)

    return new_state

apply_u(np.array([0.8, 0.6]))


array([0.6, 0.8])

In [32]:
# Codercise l.1.5 - A simple quantum algorithm

U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)


def initialize_state():
    """Prepare a qubit in state |0>.

    Returns:
        np.array[float]: the vector representation of state |0>.
    """

    return np.array([1, 0])


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.

    Try and do so using three lines of code or less!

    Returns:
        np.array[int]: the measurement results after running the algorithm 100 times
    """

    state = apply_u(initialize_state())

    meas = measure_state(state, 100)

    return meas

quantum_algorithm()

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0])